### ISSUE TITLE
Collapsed toolbar in RStudio Server isn't styled

### ISSUE THREAD

**Issue by MikeJohnPage** [gadenbuie/rsthemes#34]
When using the One Dark {rstheme} in RStudio server, the top panel fails to align colours:

<img width="884" alt="onedark" src="https://user-images.githubusercontent.com/38110953/94151624-ec2c1a80-fe7a-11ea-9537-7d13ade49ae1.png">

I tried tweaking some of the CSS classes for the page but cannot seem to find the correct element for this top panel. Any ideas / suggestions?

RStudio Server: Version 1.3.1073
Chrome: Version 85.0.4183.102

**Comment by MikeJohnPage** [comment]
Actually updating the following class fixes the issues:

```
.rstudio-themes-flat .rstudio-themes-dark-grey .GGBOEFPDN5 {
    background: #282d33;
    border-color: #282d33;
}
```

**Comment by gadenbuie** [comment]
The problem is that classes like `.GGBOEFPDN5` aren't stable. Unfortunately they change or may change between versions or builds. If you can find a CSS selector that targets that bar without relying on the compiled classes, that would be really helpful.

I'm confused though, because this is what One Dark looks like for me with 1.3.1056 (in a docker container). I doubt much changed between `.1056` and `.1073`. Where is the RStudio server running?

![image](https://user-images.githubusercontent.com/5420529/94173327-c9413c80-fe61-11ea-94b7-ac9edbcf7202.png)

**Comment by MikeJohnPage** [comment]
> If you can find a CSS selector that targets that bar without relying on the compiled classes, that would be really helpful.  

Using the below CSS (using a custom CSS extension) also fixes the colour issue:

```
#rstudio_container > div:nth-child(2) > div > div:nth-child(2) > div > div:nth-child(2) > table > tbody > tr > td {
	background: #282d33;
    border-color: #282d33;
}
```
Is this what you were after?

> Where is the RStudio server running?

It is running on an Ubuntu 18.04 LTS image in Azure.

**Comment by gadenbuie** [comment]
Oh I see it now... the toolbar can be turned on and off in the server

![image](https://user-images.githubusercontent.com/5420529/94280248-2ea53400-ff1b-11ea-834c-4eee6962a915.png)

After playing with it a bit I like this CSS selector:

```css
.rstudio-themes-flat .rstudio-themes-dark [role="banner"] + [role="navigation"] > table > tbody > tr > td {
  background: #282d33;
  border-color: #282d33;
}
```

I have a big refactor going in #35 and I'll roll this change into that PR

**Comment by MikeJohnPage** [comment]
Awesome. Thanks 👍

**Comment by gadenbuie** [comment]
Note to self: in 1.4+ it's `header + [role="navigation"]` instead of `[role="banner"] + [role="navigation"]`
